### ISSUE TITLE
cannot use pydoctest on files with argparse

### ISSUE THREAD

**Issue by testpushpleaseignore** [jepperaskdk/pydoctest#49] opened 2023-07-20 18:36 UTC
Seeing that this project uses `argparse`, I have been finding issues where running `pydoctest` on a directory which contains a .py file that also uses `argparse`. For example, I have a .py file containing something like the following:
```
from argparse import ArgumentParser

wplApiParser = ArgumentParser(description="Since the WPL_API has been imported into this script, here are the command arguments that you can add to customize how this script runs.")
wplApiParser.add_argument("--headless", help="Run Selenium within this API headless, meaning that a Chrome window will not be visible when scripting. This will allow you to run this script without being logged into a machine directly (such as running the script with Windows Task Scheduler).", action="store_true")
wplApiParser.add_argument("--dataFile", help="Path to the SQLite file that you want to script in. Not providing this argument will instead launch a window asking you for the file path.", action='store')
wplApiParser.add_argument("--hcis", help="HCIS that you want to log in - not using flag will use whatever HCIS is set in the script itself (or if not set in the script, then will use the default HCIS for user).", action='store')
wplApiParser.add_argument("--job", help="Job that you want to log in - not using flag will use whatever Job is set in the script itself (or if not set in the script, then will use the default Job for user).", action='store')
wplApiParser.add_argument("--webDriverPath", help="Path to the \"chromedriver.exe\"(Chrome) or the \"msedgedriver.exe\"(Microsoft Edge) web drivers. Not using this argument will default to searching the PATH for the executables instead.", action='store')
wplApiParser.add_argument("--scriptPath", help="Path to the script, if you tell Python to call this 'WPL_API' directly. Required if you call 'Python WPL_API.py'. If you want to run any scripts in --headless mode, you will want to have python run the 'WPL_API.py' directly, since it can then notify the Script Monitor database that it has started running.", action='store')
wplApiParser.add_argument("--notifyProcessTracker", help="Use this flag when running a script in --headless mode for a server, that can then be viewable with the Script Monitor.", action='store_true')
wplApiParser.add_argument("--logErrorToSharepoint", help="Use this flag when running the API directly, and to have it update the SharePoint error page when an uncaught exception occurs, shutting down the script.", action='store_true')
wplApiArgs = wplApiParser.parse_args()
```
-----
If a file were to start with something like the above, then `pydoctest` will output the following:
```
C:\Users\<USER>\Desktop\New folder>pydoctest --verbosity 2
usage: pydoctest [-h] [--headless] [--dataFile DATAFILE] [--hcis HCIS] [--job JOB] [--webDriverPath WEBDRIVERPATH]
                 [--scriptPath SCRIPTPATH] [--notifyProcessTracker] [--logErrorToSharepoint]
pydoctest: error: unrecognized arguments: --verbosity 2
```
-----
All of the arguments here are from my file, instead of this project's arguments. I'm assuming that my script's argparse commands is hijacking the ones in `pydoctest`, and messing everything up. Would you happen to have any suggestions on getting `pydoctest` to work with files that also use `argparse`?

**Comment by testpushpleaseignore** [comment] 2023-07-20 19:09
Well right after submitting I thought of creating a guard that does the following:
```
if __name__ == "__main__" or "WPL_API" in __name__ :
	wplApiParser = ArgumentParser(description="Since the WPL_API has been imported into this script, here are the command arguments that you can add to customize how this script runs.")
	wplApiParser.add_argument("--headless", help="Run Selenium within this API headless, meaning that a Chrome window will not be visible when scripting. This will allow you to run this script without being logged into a machine directly (such as running the script with Windows Task Scheduler).", action="store_true")
.
.
.
```
-----
Though not perfect, at least I can make sure that my `argparse` only activates for my code, though wasn't sure if there was a better solution.

**Comment by jepperaskdk** [comment] 2023-07-20 19:15
@testpushpleaseignore Thanks for posting! I can reproduce it as well.

I think adding the main guard is a good start. pydoctest loads the code to analyze it, and this is problematic since python executes all top-level statements on imports. I guess it is the same issue as described here: https://github.com/jepperaskdk/pydoctest/issues/24

I will try to investigate if there is a better way to analyze the code, preferably in a sandboxed environment not affected by the user code.

**Comment by testpushpleaseignore** [comment] 2023-07-20 20:02
Yeah no worries, but I appreciate the quick update!

**Comment by testpushpleaseignore** [comment] 2023-07-20 21:48
Also what might work slightly better is to have my guard show the following:
`if "pydoctest" not in path.basename(sys.argv[0]):`

With that I should hopefully just filter out the sort of scripts that I don't want touching argparse.

**Comment by jepperaskdk** [comment] 2023-07-21 16:00
But is the argparse in your code affected by pydoctest? Surely it shouldn't be necessary to have guards against libraries like that in your code. I think the main-guard is generally best-practice. Let me know if I'm missing something. :)

**Comment by jepperaskdk** [comment] 2023-09-09 05:38
@testpushpleaseignore Did a main guard fix the problem? Then I think we can close this, and track it further in #24. :-)

**Closed** 2024-08-12 08:20 UTC
