### ISSUE TITLE
Some fail messages are too generic

### ISSUE THREAD

**Issue by hhalaby** [jepperaskdk/pydoctest#32] opened 2022-08-19 15:32 UTC
The only output from the tool when a docstring fails currently is: `Unable to parse docstring:` which doesn't help in debugging.

After doing a bit of digging around, I found out that some information is lost through the raised Exceptions. It would be helpful to have the function that failed (e.g. `get_parameters`) and the reason it failed (e.g. `undetected type`).

A message of the sort already exists in utilities.py (`raise Exception(f"Was unable to detect the type of: {type_string} from module: {module.__file__}.\nIf you believe this is a bug, please file it here: https://github.com/jepperaskdk/pydoctest/issues")
`) but it is never shown to the user.

**Comment by jepperaskdk** [comment] 2022-08-19 19:14
Hey, thanks for submitting this! (and your PRs).

Do you have examples that can reproduce the issues? Some of exception information looks like it is being swallowed by these exceptions: https://github.com/jepperaskdk/pydoctest/blob/main/pydoctest/parsers/google_parser.py#L41

No idea why I added them - they should be removed.

**Comment by hhalaby** [comment] 2022-08-20 09:52
I was testing out the tool on simple docstrings that followed the numpy style but still failed according to the tool. I will try to put some examples here on Monday. 

But I can confirm that the issue is as you say when you re raise a newly instantiated ParserException instead of the existing exception. 

I would also not use the generic Exception as it is considered generally bad practice. We should be able to handle specific exception. And if other errors pop up then it at least it allows the user to see what the real problem is.

**Comment by jepperaskdk** [comment] 2024-08-13 04:39
Will close this - please reopen if you have examples.

**Closed by jepperaskdk** 2024-08-13 04:39 UTC
